#ifndef __BB_H__
#define __BB_H__

// Uncomment this line to enable debug output
#define DEBUG

// If this line is uncommented "pretty print mode" will be enabled. This simply
// appends a newline to the end of each line (after a `;`) in the generated 
// output. This is purely for the benefit of someone trying to debug the output
// generated by the compiler, not for the compiler of the generated output.
// This will also add tab indentions to the output to aid in the readability.
#define PRETTY_PRINT

#ifdef DEBUG
#include <iostream>
#endif

#include "token.h"

// Helper function to print a token for debug output in the lexer
inline void print_lex(Token t)
{
#ifdef DEBUG
    std::cout << "[LEX]: Found token: " << t.lexeme() << std::endl;
#endif
}

// Helper function to print parser debug messages
inline void print_parse(const char* msg) 
{
#ifdef DEBUG
    std::cout << "[PARSER]: " << msg << std::endl;
#endif
}

#endif
