#ifndef __BB_H__
#define __BB_H__

// Uncomment this line to enable debug output
#define DEBUG

// Uncomment this to force flush the generated code on each write. 
// This is a special debug feature to force the code generator to flush its 
// contents to disk after each write. This is done to ensure that the generated
// code is actually written to disk before a call to exit() during a failed
// parse, thus aiding in the debug process.
#define FORCE_GENERATOR_FLUSH

// If this line is uncommented "pretty print mode" will be enabled. This simply
// appends a newline to the end of each line (after a `;`) in the generated 
// output. This is purely for the benefit of someone trying to debug the output
// generated by the compiler, not for the compiler of the generated output.
// This will also add tab indentions to the output to aid in the readability.
#define PRETTY_PRINT

#ifdef DEBUG
#include <iostream>
#endif

#include "token.h"

// Helper function to print a token for debug output in the lexer
inline void print_lex(Token t)
{
#ifdef DEBUG
    std::cout << "[LEX]: Found token: " << t.lexeme() << std::endl;
#endif
}

// Helper function to print parser debug messages
inline void print_parse(const char* msg) 
{
#ifdef DEBUG
    std::cout << "[PARSER]: " << msg << std::endl;
#endif
}

#endif
